package store
import("database/sql";"fmt";"os";"path/filepath";"time";_ "modernc.org/sqlite")
type DB struct{*sql.DB}
type Sync struct{ID int64 `json:"id"`;Name string `json:"name"`;SourceURL string `json:"source_url"`;DestURL string `json:"dest_url"`;Schedule string `json:"schedule"`;LastStatus string `json:"last_status"`;LastRun *string `json:"last_run"`;RunCount int `json:"run_count"`;CreatedAt time.Time `json:"created_at"`}
type SyncRun struct{ID int64 `json:"id"`;SyncID int64 `json:"sync_id"`;Status string `json:"status"`;BytesMoved int64 `json:"bytes_moved"`;Error string `json:"error"`;RanAt time.Time `json:"ran_at"`}
func Open(d string)(*DB,error){os.MkdirAll(d,0755);dsn:=filepath.Join(d,"conduit.db")+"?_journal_mode=WAL&_busy_timeout=5000";db,err:=sql.Open("sqlite",dsn);if err!=nil{return nil,fmt.Errorf("open: %w",err)};db.SetMaxOpenConns(1);migrate(db);return &DB{db},nil}
func migrate(db *sql.DB){db.Exec(`CREATE TABLE IF NOT EXISTS syncs(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,source_url TEXT NOT NULL,dest_url TEXT NOT NULL,schedule TEXT DEFAULT '@daily',last_status TEXT DEFAULT '',last_run TEXT,run_count INTEGER DEFAULT 0,created_at DATETIME DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS sync_runs(id INTEGER PRIMARY KEY AUTOINCREMENT,sync_id INTEGER NOT NULL,status TEXT NOT NULL,bytes_moved INTEGER DEFAULT 0,error TEXT DEFAULT '',ran_at DATETIME DEFAULT CURRENT_TIMESTAMP)`)}
func(db *DB)Create(s *Sync)error{res,err:=db.Exec(`INSERT INTO syncs(name,source_url,dest_url,schedule)VALUES(?,?,?,?)`,s.Name,s.SourceURL,s.DestURL,s.Schedule);if err!=nil{return err};s.ID,_=res.LastInsertId();return nil}
func(db *DB)List()([]Sync,error){rows,_:=db.Query(`SELECT id,name,source_url,dest_url,schedule,last_status,last_run,run_count,created_at FROM syncs ORDER BY created_at DESC`);defer rows.Close();var out[]Sync;for rows.Next(){var s Sync;rows.Scan(&s.ID,&s.Name,&s.SourceURL,&s.DestURL,&s.Schedule,&s.LastStatus,&s.LastRun,&s.RunCount,&s.CreatedAt);out=append(out,s)};return out,nil}
func(db *DB)RecordRun(r *SyncRun){res,_:=db.Exec(`INSERT INTO sync_runs(sync_id,status,bytes_moved,error)VALUES(?,?,?,?)`,r.SyncID,r.Status,r.BytesMoved,r.Error);r.ID,_=res.LastInsertId();db.Exec(`UPDATE syncs SET last_status=?,last_run=CURRENT_TIMESTAMP,run_count=run_count+1 WHERE id=?`,r.Status,r.SyncID)}
func(db *DB)Delete(id int64){db.Exec(`DELETE FROM sync_runs WHERE sync_id=?`,id);db.Exec(`DELETE FROM syncs WHERE id=?`,id)}
func(db *DB)Stats()(map[string]interface{},error){var s int;db.QueryRow(`SELECT COUNT(*) FROM syncs`).Scan(&s);return map[string]interface{}{"syncs":s},nil}
